version: "3"

services:
  server-node:
    volumes:
      - ./api:/api
    ports:
      - 3333:3333

  db-postgres:
    ports:
      - 5432:5432
    volumes:
      - ./db/backups:/backups
    environment:
      - POSTGRES_PASSWORD=answer
      - POSTGRES_USER=answer
      - POSTGRES_DB=answer

  pgadmin:
    image: fenglc/pgadmin4
    container_name: "pgadmin"
    ports:
      - 5050:5050
    links:
      - db-postgres
    depends_on:
      - db-postgres
    environment:
      - DEFAULT_USER=a@a.com
      - DEFAULT_PASSWORD=12345678
